### ISSUE TITLE
Doc Bug: Connecting to Systems (Vehicles) · MAVSDK Guide

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/MAVSDK-docs#206]
@JonasVautherin [This problem](https://github.com/mavlink/MAVSDK-Python/issues/220) has come up a few times - people do not know how to format the strings, and all our examples use SITL.

What we need to do is add connection string info for common cases. Probably in [Connecting to Systems (Vehicles) · MAVSDK Guide](https://mavsdk.mavlink.io/develop/en/guide/connections.html), and either linked or reproduced in http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/#run-the-examples

Also add the info about how you can get it on linux using dmesg.

Some of the options to cover:
- Linux computer connected to the vehicle via Serial port - presumably for a companion like RaPi? - "serial:///dev/ttyACM0" [as above - do we need these three forward slashes at start?]
- Linux computer via USB - "serial /dev/ttyUSB0"? [Can we see this via dmesg?]
- SITL connected to the vehicle via UDP - 
- SITL connected to the vehicle via TCP - 
- OSX computer connected to the vehicle via USB - 
- Windows computer connected to the vehicle via USB (in this case on COM1) |- ?
- Windows computer connected to the vehicle telemetry radio?
- Any more.

Upshot, let's have a link that people can find this one.

Can you fill in the table, and show me an example output of using dmesg?

**Comment by moonmotor** [comment]
hamishwillee, thanks for opening this issue. Being a noob, I was having trouble connecting to an actual drone (as opposed to the SITL). This issue and the links above were all I could find, but were not very clear. After a few hours of trial and error, I made the connection. I think an example using a live drone over telemetry would be helpful. In the mean time, anyone who is trying to connect using Python and Windows 10 the syntax is:
await drone.connect(system_address="serial:///COMn") where n = your COM port
the three slashes is where I got tripped up.

**Comment by julianoes** [comment]
> the three slashes is where I got tripped up.

Oh! That's a bug. It should be 2 slashes, on Linux it's 3 because the path starts with a slash.

**Comment by moonmotor** [comment]
a-ha, seemed odd, but I'm a hardware guy just learning to code, so it could have been a smiley face for all I know. :)

**Comment by hamishwillee** [comment]
@julianoes Can you guys show me what each of the above should be: https://github.com/mavlink/MAVSDK-docs/issues/206#issue-639223237 so I can integrate this as a table?

So for windows I assume you will fix the bug and it will be ...

Connection type |  String
--- | ---
Windows computer connected to the vehicle via USB (in this case on COM1) | `serial://COMn`,  where `n` = your COM port (e.g. `serial://COM1`)

**Comment by julianoes** [comment]
@hamishwillee I think it's still `serial:///COM1` until we fix it.

**Comment by hamishwillee** [comment]
@julianoes @JonasVautherin So I updated the table. Is this correct?

Connection type |  String
--- | ---
Windows connected to the vehicle via USB (includes USB-connected Telemetry radios).  | `serial:///COMn`,  where `n` = the COM port (e.g. `serial:///COM1`)
Linux (e.g Raspberry Pi) connected to the vehicle via Serial port | `serial:///dev/ttyACMn`,  where `n` = the port (e.g. `serial:///dev/ttyACM0`)
Linux connected to the vehicle via USB | `serial:///dev/ttyUSBn`,  where `n` = the port (e.g. `serial:///dev/ttyUSB0`)
SITL connected to the vehicle via UDP | `udp://:14540`

I'd like to integrate this. Can you confirm:
- I think we don't support TCP connections for SITL, so no need for "SITL connected to the vehicle via TCP"
- How are ports reference in macOS? Same as linux for USB and serial ports?
- are there any other cases.

**Comment by julianoes** [comment]
Thanks @hamishwillee.

> I think we don't support TCP connections for SITL, so no need for "SITL connected to the vehicle via TCP"

Correct.

> How are ports reference in macOS? Same as linux for USB and serial ports?

I think they are usually `/dev/tty.usbserial-...` or `/dev/tty.usbmodem-...`

**Comment by dimikout3** [comment]
I am trying to connect via serial (ttyUSB0) from pixhawk to a jetson xavier. I have installed mavsdk-python via pip3 and I am trying to execute examples/takeoff_and_land.py. With the only difference that 

`await drone.connect(system_address="udp://:14545")
`
has been changed to 

`await drone.connect(system_address="serial:///dev/ttyUSB0")
`
However I am getting the following error
```
This installation does not provide an embedded 'mavsdk_server' binary.
If you installed using pip, this means that 'mavsdk_server' is not distributed
for your platform yet (e.g. arm).

You will need to get and run the 'mavsdk_server' binary manually:

  1. Download 'mavsdk_server' from: https://github.com/mavlink/mavsdk/releases
     or build it from source.

  2. Run it, e.g. on port 50051:
     './mavsdk_server -p 50051'

  3. Set the 'mavsdk_server_address' and port when creating the System:
     'drone = System(mavsdk_server_address='localhost', port=50051)'
```


Any ideas why this is happening ? 
P.S I have checked that the FTDI is connected to ttyUSB0. I have enabled the mavlink connection (MAV_1_CONFIG = TELEM 2). I am using a HITL approach via AirSim (Although I believe that this is not relevant)
