### ISSUE TITLE
takeoff command denied

### ISSUE THREAD

**Issue by moonmotor** [mavlink/MAVSDK-docs#207]
I've been trying to run the takeoff_and_land.py example on a live drone. The drone connects, it arms briefly (1-3 sec), then the motors stop and the result is COMMAND_DENIED: origin: takeoff(): params().
I can takeoff and even run missions directly from QGC without issue. Seems there's something QGC is doing that the example code is not.

**Comment by julianoes** [comment]
Do you have a GPS signal?

Can you check if you can arm with QGC or if it shows any warnings/errors?

**Comment by moonmotor** [comment]
yes, 15 sats. I can arm with QGC, takeoff and run missions.

**Comment by moonmotor** [comment]
MESSAGES
C:\AgVueApp>python takeoff_and_land.py
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
Drone discovered with UUID: 1
Waiting for drone to have a global position estimate...
Global position estimate ok
Version: [flight_sw_major: 4, flight_sw_minor: 0, flight_sw_patch: 3, flight_sw_vendor_major: 100, flight_sw_vendor_minor: 102, flight_sw_vendor_patch: 102, os_sw_major: 0, os_sw_minor: 0, os_sw_patch: 0, flight_sw_git_hash: 003236383 , os_sw_git_hash: 003438656366346 ]
-- Arming
-- Taking off
Traceback (most recent call last):
  File "takeoff_and_land.py", line 43, in <module>
    loop.run_until_complete(run())
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "takeoff_and_land.py", line 34, in run
    await drone.action.takeoff()
  File "C:\Python\Python38\lib\site-packages\mavsdk\action.py", line 298, in takeoff
    raise ActionError(result, "takeoff()")
mavsdk.action.ActionError: COMMAND_DENIED: 'Command Denied'; origin: takeoff(); params: ()

**Comment by moonmotor** [comment]
Question: I see a set_takeoff_altitude action, but it is not set in the example. Is there a default altitude?

**Comment by moonmotor** [comment]
Ok, sorry to bombard with messages, pls. let me know if I'm breaking etiquette.
I added a sleep(5) after  action.arm() and added messages before and after the takeoff command. Now it stays armed (motors spinning) until the takeoff command is issued, then the motors stop. Motors should spool up when takeoff is issued. Looks like script continues into landing mode after the sleep(10). I no longer get a COMMAND_DENIED message. Here's the output messages:

C:\AgVueApp>python takeoff_and_land.py
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
Drone discovered with UUID: 255
Waiting for drone to have a global position estimate...
Global position estimate ok
-- Arming
-- Taking off - THIS IS BEFORE TAKEOFF COMMAND
-- Taking off STILL- THIS IS AFTER TAKEOFF COMMAND--
-- Landing
Press any key to continue . . .

As a side note, it stays in LAND mode after landing and will not arm again until the mode is reset in QGC or through an RC TX (much easier to flip a mode switch on the RC TX).
Thanks for your help!

**Comment by moonmotor** [comment]
I'm an idiot - was running Ardupilot, didn't realize MAVSDK only supports PX4. Loaded PX4 and all is well!
