### ISSUE TITLE
Noticed potentially outdated documentation within MAVSDK on C++

### ISSUE THREAD

**Issue by Swabhan** [mavlink/MAVSDK-docs#281]
I recently updated MAVSDK on my project and noticed that using mavsdk within my project does not match the documentation. 

The documentation recommends initialization like:

`
Mavsdk mavsdk;

ConnectionResult connection_result = mavsdk.add_any_connection("udp://:14540");
`

but the above code does not work anymore because the default constructor has been deleted. Reading through the repo I was able to resolve my issue, but just wanted to make sure that the documentation is outdated and I am using MAVSDK correctly. If the documentation is outdated, I am open to spending sometime refining portions of the documentation.

**Comment by hamishwillee** [comment]
@julianoes or @JonasVautherin FYI

**Comment by julianoes** [comment]
Thanks. Contributions to fix it are always welcome.

Probably a few places: https://github.com/search?q=repo%3Amavlink%2FMAVSDK-docs%20Mavsdk%20mavsdk%3B&type=code

**Comment by KarthiAru** [comment]
Created a PR - https://github.com/mavlink/MAVSDK-docs/pull/286

**Comment by julianoes** [comment]
Merged, thanks!
