### ISSUE TITLE
How to get the ip/port of a connected component

### ISSUE THREAD

**Issue by tourivertes** [mavlink/MAVSDK-docs#284]
Hey guys, more of a question here than an issue really.

is there a way to get the ip-address/port of a component connected via udp connection when running mavsdk in server mode?

To be specific, I'm running this code to start a server:

`mavsdk.add_any_connection("udp://0.0.0.0:14590", ForwardingOption::ForwardingOn);`

I then connect to the port via GCS, and I see the following line in the console logs showing the ip/port that I want to get:

`[02:18:17|Info ] New system on: 192.168.1.53:14590 (with system ID: 255) (udp_connection.cpp:199)`

Perhaps there's a way to even get the `UdpConnection` instance itself?

**Comment by julianoes** [comment]
That's not currently exposed. What's the use case?

**Comment by tourivertes** [comment]
I need to stream a camera feed from the companion computer to the ground station. I was thinking I should:

- Get the ip address of the client ground station component at connection time
- Stream the camera feed to the client address using gstreamer

**Comment by julianoes** [comment]
Ok, and you don't want to do it the other way round where you have an RTSP server on the drone, and then you advertise the RTSP URL using the camera server.

E.g. like this: https://github.com/SiFly-Aviation/siyi-a8-mini-camera-manager/blob/ab53a03aaf2e7123bda0b825527daeac8451e1bd/camera-manager/camera_manager.cpp#L247-L250

**Comment by tourivertes** [comment]
I want to use UDP to do it, it being lower latency and all.

The log callback solution is... not exactly what I had in mind 🙂. I'll fork the repo and try to change the function signature responsible for creating the connection locally; have it return a pointer to the connection or something.

Thanks for the help.

**Comment by julianoes** [comment]
If you find a nice API, I'd consider merging it. I'm just reluctant in increasing the API surface that I have to maintain.
